package com.eby.orm.entity;
// Generated Aug 16, 2015 9:15:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dosen generated by hbm2java
 */
public class Dosen  implements java.io.Serializable {


     private int nip;
     private String nama;
     private String alamat;
     private String mataAjar;
     private Set mahasiswas = new HashSet(0);

    public Dosen() {
    }

	
    public Dosen(int nip) {
        this.nip = nip;
    }
    public Dosen(int nip, String nama, String alamat, String mataAjar, Set mahasiswas) {
       this.nip = nip;
       this.nama = nama;
       this.alamat = alamat;
       this.mataAjar = mataAjar;
       this.mahasiswas = mahasiswas;
    }
   
    public int getNip() {
        return this.nip;
    }
    
    public void setNip(int nip) {
        this.nip = nip;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getMataAjar() {
        return this.mataAjar;
    }
    
    public void setMataAjar(String mataAjar) {
        this.mataAjar = mataAjar;
    }
    public Set getMahasiswas() {
        return this.mahasiswas;
    }
    
    public void setMahasiswas(Set mahasiswas) {
        this.mahasiswas = mahasiswas;
    }




}


