package com.eby.orm.entity;
// Generated Aug 16, 2015 9:15:54 PM by Hibernate Tools 4.3.1



/**
 * Mahasiswa generated by hbm2java
 */
public class Mahasiswa  implements java.io.Serializable {


     private String nim;
     private Dosen dosen;
     private String nama;
     private String kelas;
     private String alamat;
     private String tglLahir;

    public Mahasiswa() {
    }

	
    public Mahasiswa(String nim, Dosen dosen) {
        this.nim = nim;
        this.dosen = dosen;
    }
    public Mahasiswa(String nim, Dosen dosen, String nama, String kelas, String alamat, String tglLahir) {
       this.nim = nim;
       this.dosen = dosen;
       this.nama = nama;
       this.kelas = kelas;
       this.alamat = alamat;
       this.tglLahir = tglLahir;
    }
   
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }
    public Dosen getDosen() {
        return this.dosen;
    }
    
    public void setDosen(Dosen dosen) {
        this.dosen = dosen;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getKelas() {
        return this.kelas;
    }
    
    public void setKelas(String kelas) {
        this.kelas = kelas;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getTglLahir() {
        return this.tglLahir;
    }
    
    public void setTglLahir(String tglLahir) {
        this.tglLahir = tglLahir;
    }




}


